version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 2021:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ecommerce
    networks:
      - ecommercesbd
networks:
  ecommercesbd: